[package]
org = "thiyan"
name = "fhir_validator_service"
version = "0.1.0"
distribution = "2201.3.4"

[[dependency]]
org = "wso2healthcare"
name = "healthcare.fhir.r4"
version = "0.1.16"

[build-options]
observabilityIncluded = true
